/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.Banco;
import datos.Cuenta;
import datos.CuentaAhorro;
import datos.CuentaHipoteca;
import datos.CuentaPrestamo;

/**
 *
 * @author Cuarto A
 */
public class datos extends javax.swing.JDialog {
    
    private String tipo;
    private Cuenta cu = null;
    private boolean editar = false;

    /**
     * Creates new form depositar
     */
    public datos(java.awt.Frame parent, boolean modal, String tipo1) {
        super(parent, modal);
        initComponents();
        tipo = tipo1;
        this.setTitle("Depositar en " + tipo);
    }
    
    public datos(java.awt.Frame parent, boolean modal, String tipo1, Cuenta c) {
        super(parent, modal);
        initComponents();
        tipo = tipo1;
        this.cu = c;
        this.editar = true;
        cargarDatos();
        this.setTitle("Editar datos de " + tipo);
        this.ftxt_Balance.setEditable(false);
    }
    
    private void cargarDatos() {
        txt_Cliente.setText(cu.getCliente());
        cbx_Tipo_Cliente.setSelectedItem(cu.getTipoCliente());
        ftxt_Balance.setValue(cu.getBalance());
        spn_Porcentage_Taza_Interes.setValue((cu.getTasaInteres() * 100));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt_Cliente = new javax.swing.JTextField();
        cbx_Tipo_Cliente = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        ftxt_Balance = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        spn_Porcentage_Taza_Interes = new javax.swing.JSpinner();
        jLabel4 = new javax.swing.JLabel();
        btn_Guardar = new javax.swing.JButton();
        btn_Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Cliente:");

        cbx_Tipo_Cliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Natural", "Empresa" }));

        jLabel2.setText("Balance:");

        ftxt_Balance.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));

        jLabel3.setText("Taza de Interes.");

        jLabel4.setText("%");

        btn_Guardar.setText("Guardar");
        btn_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GuardarActionPerformed(evt);
            }
        });

        btn_Cancelar.setText("Cancelar");
        btn_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_Cliente)
                    .addComponent(ftxt_Balance))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbx_Tipo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(btn_Guardar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                .addComponent(btn_Cancelar)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(spn_Porcentage_Taza_Interes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbx_Tipo_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ftxt_Balance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(spn_Porcentage_Taza_Interes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Guardar)
                    .addComponent(btn_Cancelar)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_CancelarActionPerformed

    private void btn_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GuardarActionPerformed
        // TODO add your handling code here:
        double taza = Double.parseDouble(spn_Porcentage_Taza_Interes.getValue().toString()) / 100;
        int pos = 0;
        if (editar) {
            pos = Banco.getListaCuenta().indexOf(cu);
        }
        switch (this.tipo) {
            case "Cuenta Ahorro":
                if (editar) {
                    Banco.editar(pos, new CuentaAhorro(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                } else {
                    Banco.agregar(new CuentaAhorro(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                }
                break;
            case "Cuenta Hipoteca":
                if (editar) {
                    Banco.editar(pos, new CuentaHipoteca(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                } else {
                    Banco.agregar(new CuentaHipoteca(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                }
                break;
            case "Cuenta Prestamo":
                if (editar) {
                    Banco.editar(pos, new CuentaPrestamo(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                } else {
                    Banco.agregar(new CuentaPrestamo(txt_Cliente.getText(), cbx_Tipo_Cliente.getSelectedItem().toString(), Double.parseDouble(ftxt_Balance.getValue().toString()), taza));
                }
                break;
            default:
                break;
        }
        this.dispose();
    }//GEN-LAST:event_btn_GuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(datos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                datos dialog = new datos(new javax.swing.JFrame(), true, null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Cancelar;
    private javax.swing.JButton btn_Guardar;
    private javax.swing.JComboBox<String> cbx_Tipo_Cliente;
    private javax.swing.JFormattedTextField ftxt_Balance;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSpinner spn_Porcentage_Taza_Interes;
    private javax.swing.JTextField txt_Cliente;
    // End of variables declaration//GEN-END:variables
}
