/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import datos.Banco;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Cuarto A
 */
public class index extends javax.swing.JFrame {

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
        JFileChooser selectorArchivos = new JFileChooser();
        selectorArchivos.setFileSelectionMode(JFileChooser.FILES_ONLY);
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos CSV", "csv");
        selectorArchivos.setFileFilter(filtro);
        int resultado = selectorArchivos.showOpenDialog(this);
        Banco.archivo = selectorArchivos.getSelectedFile().getName();
        Banco.leerCuentas();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mi_Agregar = new javax.swing.JMenuItem();
        mi_Ahorros = new javax.swing.JMenuItem();
        mi_Prestamos = new javax.swing.JMenuItem();
        miHipotecas = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mi_Salir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Actividades");

        mi_Agregar.setText("Agregar Cuenta");
        mi_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_AgregarActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Agregar);

        mi_Ahorros.setText("Cuentas de Ahorro");
        mi_Ahorros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_AhorrosActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Ahorros);

        mi_Prestamos.setText("Cuentas de Prestamos");
        mi_Prestamos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_PrestamosActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Prestamos);

        miHipotecas.setText("Cuentas de Hipotecas");
        miHipotecas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miHipotecasActionPerformed(evt);
            }
        });
        jMenu1.add(miHipotecas);
        jMenu1.add(jSeparator1);

        mi_Salir.setText("Salir");
        mi_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mi_SalirActionPerformed(evt);
            }
        });
        jMenu1.add(mi_Salir);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mi_AhorrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_AhorrosActionPerformed
        // TODO add your handling code here:
        new ahorros(this, true, "Cuenta Ahorro").setVisible(true);
    }//GEN-LAST:event_mi_AhorrosActionPerformed

    private void mi_PrestamosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_PrestamosActionPerformed
        // TODO add your handling code here:
        new ahorros(this, true, "Cuenta Prestamo").setVisible(true);
    }//GEN-LAST:event_mi_PrestamosActionPerformed

    private void miHipotecasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miHipotecasActionPerformed
        // TODO add your handling code here:
        new ahorros(this, true, "Cuenta Hipoteca").setVisible(true);
    }//GEN-LAST:event_miHipotecasActionPerformed

    private void mi_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mi_SalirActionPerformed

    private void mi_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mi_AgregarActionPerformed
        // TODO add your handling code here:
        String opciones[] = {"Cuenta Ahorro", "Cuenta Prestamo", "Cuenta Hipoteca"};
        int opt = JOptionPane.showOptionDialog(this, "Seleccione el tipo de Cuenta que desea crear", "Tipo de Nueva Cuenta", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opciones, opciones[0]);
        new datos(this, rootPaneCheckingEnabled, opciones[opt]).setVisible(true);
    }//GEN-LAST:event_mi_AgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new index().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem miHipotecas;
    private javax.swing.JMenuItem mi_Agregar;
    private javax.swing.JMenuItem mi_Ahorros;
    private javax.swing.JMenuItem mi_Prestamos;
    private javax.swing.JMenuItem mi_Salir;
    // End of variables declaration//GEN-END:variables
}
